project: myverein
created: '2026-09-18'
combination: backend+website+mobile+admin
repos:
  backend:
    template: _template_better-auth-backend
    path: ./myverein-backend
    suite_version: 9f10c5c77f649d6fa437ffc4464ee98be2a5107f
    remote: https://github.com/makers-ev/myverein-backend
  website:
    template: _template_better-auth-website
    path: ./myverein-website
    suite_version: b006c2d434b07235a4050ae5e310042e3f125c67
    remote: https://github.com/makers-ev/myverein-website
  mobile:
    template: _template_better-auth-mobile
    path: ./myverein-mobile
    suite_version: 94d3b62c26af846c3834e716f58e65b415556f02
    remote: https://github.com/makers-ev/myverein-mobile
  admin:
    template: _template_better-auth-admin
    path: ./myverein-admin
    suite_version: 6ac4956684457e232a01ba534dd07208e61f12ed
    remote: https://github.com/makers-ev/myverein-admin
options:
  email_provider: dev-fallback
  organization_plugin: false
  strip_examples: false
